### PR TITLE
added amd support

### PR DESCRIPTION
**Pull request by andrew-makarenko**

### CODE REVIEW

**Comment by robotnic** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi Andrew

I go a pull request. Did you test it?
Is it ready to merge or should I check that?

Bernhard

On 24.07.2013 13:38, Andrew Makarenko wrote:

> You can merge this Pull Request by running:
> 
> git pull https://github.com/andrew-makarenko/waterbug master
> 
> Or you can view, comment on it, or merge it online at:
> 
> https://github.com/robotnic/waterbug/pull/1
> 
> -- Commit Summary --
> - added amd support
> 
> -- File Changes --
> 
> M waterbug.js (12)
> 
> -- Patch Links --
> 
> https://github.com/robotnic/waterbug/pull/1.patch 
> https://github.com/robotnic/waterbug/pull/1.diff

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)

iQEcBAEBAgAGBQJR79N5AAoJENYMNdS3eBtkcxwH+gK8Nqv8kiCvpICRFpG7uE1X
5xnKb140NiMvX4AyFee8rWGxV1gFXLvkERDNYZeqnkHH66hHLhXb6QMXC2ai2wC3
TBI9EQ2ybMvJsVUguGXOcnIM3HO0AeTyw5tKDCwLHuTQ/Lwdvp41aDzdC29fBAtJ
hh7Yn6g6BclVCbohVD6dQa9/dsKRnpSlCigO0gdKTwMhEJyOZD9jAHZZLXDw3CGp
YW7x3uCVP6DSgRLl0S/knuourspSYCYYgcbmE8d3T8tchlz3zk8wm3/xSzK0aFh6
iv7IqkBZrt76AmoTTEETM/wQucdHxj31LwgwnHRQp8RTJLgceNVD9yzQmpnkjMI=
=bujg
-----END PGP SIGNATURE-----

**Comment by andrew-makarenko** [comment]
Yes, I tested it, works like a charm :+1:

**Comment by andrew-makarenko** [comment]
@robotnic, so will it be merged?

**Comment by robotnic** [comment]
Sorry, forgot about that.

**Pull request merged**
